In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [12]:
pip install --upgrade pip numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np

In [14]:
np.__version__

'2.4.0'

In [15]:
python_list = [1, 2, 3, 4, 5]

In [16]:
print(numslist*3)
print(type(numslist))

NameError: name 'numslist' is not defined

In [ ]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [ ]:
arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
arr2D=np.array([[1,2,3],
                [1,2,3]])
print(arr2D)

[[1 2 3]
 [1 2 3]]


In [ ]:
arr3D=np.array([[[1,2,3],[1,2,3]],
                [[1,2,3],[1,2,3]]])
print(arr3D)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [ ]:
x = np.array([])
type(x)

numpy.ndarray

In [ ]:
arr3D.ndim

3

In [ ]:
shape1D = arr1D.shape
print(shape1D)

size1D = arr1D.size
print(size1D)

print(type(arr1D))
print(arr1D.dtype)

(5,)
5
<class 'numpy.ndarray'>
int64


In [ ]:
# random class in numpy
# numbers

np.random.seed(40)

# randomArray = np.random.rand(3,4)
# randomArray

randomArray = np.random.randint(0,100,(3,3)) #start, stop (shape)
randomArray

array([[70, 91,  7],
       [37, 56, 50],
       [65, 12, 71]])

In [ ]:
# aggregations

data = np.array([]