In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 40.9 MB/s  0:00:00

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install --upgrade pip numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 29.6 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [9]:
print(numslist*3)
print(type(numslist))

NameError: name 'numslist' is not defined

In [8]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [11]:
arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [12]:
arr2D=np.array([[1,2,3],
                [1,2,3]])
print(arr2D)

[[1 2 3]
 [1 2 3]]


In [14]:
arr3D=np.array([[[1,2,3],[1,2,3]],
                [[1,2,3],[1,2,3]]])
print(arr3D)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [17]:
x = np.array([])
type(x)

numpy.ndarray

In [21]:
arr3D.ndim

3

In [26]:
shape1D = arr1D.shape
print(shape1D)

size1D = arr1D.size
print(size1D)

print(type(arr1D))
print(arr1D.dtype)

(5,)
5
<class 'numpy.ndarray'>
int64


In [29]:
# random class in numpy
# numbers

np.random.seed(40)

# randomArray = np.random.rand(3,4)
# randomArray

randomArray = np.random.randint(0,100,(3,3)) #start, stop (shape)
randomArray

array([[70, 91,  7],
       [37, 56, 50],
       [65, 12, 71]])

In [ ]:
# aggregations

data = np.array([]